mutation InsertMedal($entity: MedalInsertInput!) {
  insertMedal(entity: $entity) {
    __typename
    ... on MedalGQLModel {
      id
      year
      medalType {
        id
        name
        nameEn
      }
    }
    ... on InsertError {
      errorMessage
    }
  }
}
