mutation StudyInsert($name: String!, $nameEn: String!, $program: String!, $start: DateTime!, $end: DateTime!, $userId: UUID) {
  studyInsert(
    entity: {name: $name, nameEn: $nameEn, program: $program, start: $start, end: $end, userId: $userId}
  ) {
    __typename
    ... on StudyGQLModel {
      id
      name
      nameEn
      program
      start
      end
    }
    ... on InsertError {
      failed
      msg
    }
  }
}