mutation InsertMedalType($id: UUID, $name: String!, $name_en: String, $medal_category_id: UUID!) {
  medalTypeInsert(medalType: {id: $id, name: $name, nameEn: $name_en, medalTypeGroupId: $medal_category_id}) {
    __typename
    ... on MedalTypeGQLModel {
      id
      name
      nameEn
      lastchange
      medalTypeGroup {
        id
        name
      }
    }
    ... on InsertError {
      msg
    }
  }
}
