query GetMedalTypeById($id: UUID!) {
  medalTypeById(id: $id) {
    ...MedalTypeFields
  }
}

fragment MedalTypeFields on MedalTypeGQLModel {
  id
  name
  nameEn
  lastchange
  medalTypeGroup {
    name
  }
}
