query GetCertificateTypeGroupById($id: UUID!) {
  certificateTypeGroupById(id: $id) {
    ...CertificateTypeGroupFields
  }
}

fragment CertificateTypeGroupFields on CertificateTypeGroupGQLModel {
  id
  name
  nameEn
}
