mutation InsertRankType($name: String!, $nameEn: String!, $id: UUID) {
  rankTypeInsert(rankType: {name: $name, nameEn: $nameEn, id: $id}) {
    __typename
    ... on InsertError {
      msg
    }
    ... on RankTypeGQLModel {
      id
      name
      nameEn
    }
  }
}